//Car actions
export const FETCH_CARS_WITH_DIST = "FETCH_CARS_WITH_DIST";
export const REQUEST_CARS_WITH_DIST = "REQUEST_CARS_WITH_DIST";
export const RECIEVE_CARS_WITH_DIST = "RECIEVE_CARS_WITH_DIST";
export const SAVE_SELECTED_CAR_IN_STORE = "SAVE_SELECTED_CAR_IN_STORE";
export const SAVE_SELECTED_CAR_DISTANCE_IN_STORE =
  "SAVE_SELECTED_CAR_DISTANCE_IN_STORE";
export const SAVE_CHECKOUT_CAR = "SAVE_CHECKOUT_CAR";
export const FETCH_ERROR_OCCUR = "FETCH_ERROR_OCCUR";
export const DELETE_CHECKOUT_CAR = "DELETE_CHECKOUT_CAR";
//Auth actions
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
//location actions
export const SAVE_USER_LOCATION = "SAVE_USER_LOCATION";
// confirmation actions
export const ADD_CONFIRMATION_SUCCESS = "ADD_CONFIRMATION_SUCCESS ";
export const ADD_CONFIRMATION_FAILURE = "ADD_CONFIRMATION_FAILURE";
export const ADD_CONFIRMATION_STARTED = "ADD_CONFIRMATION_STARTED";
export const REQUEST_CONFIRMATIONS = "FETCH_CONFIRMATIONS";
export const RECIEVE_CONFIRMATIONS = "RECIEVE_CONFIRMATIONS";
