export const FETCH_CARS_WITH_DIST = "FETCH_CARS_WITH_DIST";
export const SAVE_SELECTED_CAR_IN_STORE = "SAVE_SELECTED_CAR_IN_STORE";

export const SAVE_SELECTED_CAR_DISTANCE_IN_STORE =
  "SAVE_SELECTED_CAR_DISTANCE_IN_STORE";
